const PRODUCTIMG = {
    acrylicPaint: require('./acrylicPaint.png').default,
    beigeVinyl: require('./beigeVinyl.png').default,
    brush: require('./brush.png').default,
    brushes: require('./brushes.png').default,
    bush: require('./bush.png').default,
    coaster: require('./coaster.png').default,
    coralVinyl: require('./coralVinyl.png').default,
    cottonFabric: require('./cottonFabric.png').default,
    cricutEasyPress: require('./cricutEasyPress.png').default,
    cricutMachine: require('./cricutMachine.png').default,
    cricutMaker: require('./cricutMaker.png').default,
    cricutMat: require('./cricutMat.png').default,
    cricutTools: require('./cricutTools.png').default,
    cricutWeeder: require('./cricutWeeder.png').default,
    embroideryFloss: require('./embroideryFloss.png').default,
    embroideryFlossYellow: require('./embroideryFlossYellow.png').default,
    flowers: require('./flowers.png').default,
    glueGun: require('./glueGun.png').default,
    glueStick: require('./glueStick.png').default,
    infusibleInk: require('./infusibleInk.png').default,
    infusibleInkRose: require('./infusibleInkRose.png').default,
    infusibleInkTransferGreen: require('./infusibleInkTransferGreen.png').default,
    infusibleInkTransferViolet: require('./infusibleInkTransferViolet.png').default,
    needles: require('./needles.png').default,
    parchmentPaper: require('./parchmentPaper.png').default,
    premiumAcrylicPaint: require('./premiumAcrylicPaint.png').default,
    scissors: require('./scissors.png').default,
    transferTape: require('./transferTape.png').default,
    vase: require('./vase.png').default,
    woodenPlague: require('./woodenPlaque.png').default,

}

export default PRODUCTIMG;